spring.datasource.url=jdbc:postgresql://localhost:5432/client_persona
    spring.datasource.username=myuser
    spring.datasource.password=mypassword
    spring.jpa.hibernate.ddl-auto=update
    spring.kafka.bootstrap-servers=localhost:9092